### ISSUE TITLE
Implementation of propagation loss

### ISSUE THREAD

**Issue by kaixin96** [mklissa/phi_gcn#1]
Hi, I have a question regarding the implementation of propagation loss. In the code, it is implemented as
https://github.com/mklissa/phi_gcn/blob/5e3249472174a470051451ba683bf4d0c940707a/pygcn/train.py#L54
This is equivalent to Lf(X). However, as shown in GCN paper, the regularization term is equal to f(X)^T L f(X).

Is there any consideration behind this implementation choice? Thank you.

**Comment by mklissa** [comment]
Hi @kaixin96, thanks for your interest in the work! Your comment is right and after looking into it, I believe the wrong version of train.py was transferred to the public repository. This should be fixed now.
